[package]
name = "sci"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.10"
git2 = "0.17.2"
tokio = { version = "1.28.2", features = ["time", "net", "full"] }
